## Exercise No.3

**1-write program for circle class. This class has the following:**
* Attribute: its name is pi with value 3.14
* During the object create the raduis attribute is asigned by the raduis of circle
* Has two methods to calculate the Area and Circumference of circle

In [1]:
class Circle:
    # Class attribute
    pi = 3.14
    
    # Constructor to initialize radius
    def __init__(self, radius):
        self.radius = radius
    
    # Method to calculate area
    def calculate_area(self):
        return Circle.pi * self.radius ** 2
    
    # Method to calculate circumference
    def calculate_circumference(self):
        return 2 * Circle.pi * self.radius

# Example usage:
circle1 = Circle(5)  # Creating a Circle object with radius 5
print("Area of Circle:", circle1.calculate_area())  # Outputs: 78.5
print("Circumference of Circle:", circle1.calculate_circumference())  # Outputs: 31.4

Area of Circle: 78.5
Circumference of Circle: 31.400000000000002


**2. Write a program for a Rectangle class.**

Attributes: length and width (set through constructor)

Methods:

area() – returns the area

perimeter() – returns the perimeter

In [2]:
class Rectangle:
    def __init__(self, length, width):
        """Initialize the rectangle with length and width"""
        self.length = length
        self.width = width
    
    def area(self):
        """Calculate and return the area of the rectangle"""
        return self.length * self.width
    
    def perimeter(self):
        """Calculate and return the perimeter of the rectangle"""
        return 2 * (self.length + self.width)

# Example usage:
rect1 = Rectangle(10, 5)  # Creating a Rectangle object with length 10 and width 5
print("Area of Rectangle:", rect1.area())  # Outputs: 50
print("Perimeter of Rectangle:", rect1.perimeter())  # Outputs: 30

Area of Rectangle: 50
Perimeter of Rectangle: 30


**3-Write a program for an Employee class using class method.**
Attributes: name and salary

Class attribute: company_name

Use a class method to change the company_name for all employees

In [3]:
class Employee:
    company_name = "TechCorp"  # Class attribute shared across all instances
    
    def __init__(self, name, salary):
        """Initialize an Employee with name and salary"""
        self.name = name
        self.salary = salary
    
    @classmethod
    def change_company_name(cls, new_name):
        """Change the company name for all employees"""
        cls.company_name = new_name

    def display_info(self):
        """Display the employee's details"""
        return f"Employee Name: {self.name}, Salary: {self.salary}, Company: {self.company_name}"

# Example usage:
emp1 = Employee("Alice", 50000)
emp2 = Employee("Bob", 60000)

print(emp1.display_info())  # Output: Employee Name: Alice, Salary: 50000, Company: TechCorp
print(emp2.display_info())  # Output: Employee Name: Bob, Salary: 60000, Company: TechCorp

# Changing the company name using class method
Employee.change_company_name("GlobalTech")

print(emp1.display_info())  # Output: Employee Name: Alice, Salary: 50000, Company: GlobalTech
print(emp2.display_info())  # Output: Employee Name: Bob, Salary: 60000, Company: GlobalTech

Employee Name: Alice, Salary: 50000, Company: TechCorp
Employee Name: Bob, Salary: 60000, Company: TechCorp
Employee Name: Alice, Salary: 50000, Company: GlobalTech
Employee Name: Bob, Salary: 60000, Company: GlobalTech


**4- Create a Shape class and two child classes Square and Circle.**

Use polymorphism to define a method area()

Use a loop to calculate area for both shapes using a common function

In [ ]:
import math
class Shape:
    def area(self):
        """Method to be overridden by child classes"""
        pass
class Square(Shape):
    def __init__(self, side_length):
        self.side_length = side_length
    
    def area(self):
        """Calculates and returns area of the square"""
        return self.side_length ** 2

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius
    
    def area(self):
        """Calculates and returns area of the circle"""
        return math.pi * self.radius ** 2


shapes = [Square(4), Circle(5), Square(6), Circle(7)]

def calculate_areas(shape_list):
    for shape in shape_list:
        print(f"Area of {type(shape).__name__}: {shape.area():.2f}")
calculate_areas(shapes)

Area of Square: 16.00
Area of Circle: 78.54
Area of Square: 36.00
Area of Circle: 153.94


**5-Create a 1D NumPy array of numbers from 0 to 9**

In [ ]:
import numpy as np
array = np.arange(10)
print("1D NumPy array:", array)

1D NumPy array: [0 1 2 3 4 5 6 7 8 9]


**6-Create a 4x4 NumPy array of all True values**

In [ ]:
array = np.full((4, 4), True, dtype=bool)
print("4x4 NumPy array of True values:\n", array)

4x4 NumPy array of True values:
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


**7-Create an array of 10 random floats between 0 and 1**

In [7]:
random_floats = np.random.rand(10)
print("Array of 10 random floats between 0 and 1:\n", random_floats)

Array of 10 random floats between 0 and 1:
 [0.68331247 0.21722298 0.45855295 0.15073278 0.08822639 0.03474549
 0.90637588 0.91177284 0.67244016 0.21125809]


**8-Create a NumPy array of even numbers from 2 to 20**

In [8]:
even_numbers = np.arange(2, 21, 2)
print("NumPy array of even numbers from 2 to 20:\n", even_numbers)

NumPy array of even numbers from 2 to 20:
 [ 2  4  6  8 10 12 14 16 18 20]


**9-Get the maximum, minimum, and mean of an random array**

In [9]:
random_array = np.random.randint(1, 100, size=10)
max_value = random_array.max()
min_value = random_array.min()
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Maximum Value:", max_value)
print("Minimum Value:", min_value)
print("Mean Value:", mean_value)



Random Array: [66  7  7 11 24 85 37 72 75 93]
Maximum Value: 93
Minimum Value: 7
Mean Value: 47.7


**10-Flatten a 2D array to 1D**

In [10]:
arr2d = np.array([[1, 2], [3, 4]])

# Flattening the array to 1D
arr_1d = arr2d.flatten()

# Displaying the result
print("Original 2D Array:\n", arr2d)
print("Flattened 1D Array:\n", arr_1d)



Original 2D Array:
 [[1 2]
 [3 4]]
Flattened 1D Array:
 [1 2 3 4]
